-- CollegeMate PostgreSQL / Supabase Database Schema Migration
-- Defines all 10 tables, relationships, indexes, storage buckets, and RLS policies.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. TABLE: profiles
-- ==========================================
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT,
    role TEXT DEFAULT 'student',
    admission_type TEXT DEFAULT 'CET',
    category TEXT DEFAULT 'OPEN',
    gender TEXT DEFAULT 'Male',
    home_university TEXT DEFAULT 'SPPU (Pune)',
    score NUMERIC DEFAULT 0,
    branch_preference TEXT DEFAULT 'Computer Engineering',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. TABLE: colleges
-- ==========================================
CREATE TABLE public.colleges (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    college_code TEXT NOT NULL UNIQUE,
    college_name TEXT NOT NULL,
    city TEXT NOT NULL,
    district TEXT,
    university TEXT NOT NULL,
    college_type TEXT,
    website TEXT,
    placement_percentage NUMERIC,
    average_package NUMERIC,
    fees NUMERIC NOT NULL,
    hostel_available BOOLEAN DEFAULT FALSE,
    description TEXT,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. TABLE: branches
-- ==========================================
CREATE TABLE public.branches (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    branch_name TEXT NOT NULL UNIQUE,
    branch_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 4. TABLE: cutoff_years
-- ==========================================
CREATE TABLE public.cutoff_years (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    year INTEGER NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 5. TABLE: cutoffs
-- ==========================================
CREATE TABLE public.cutoffs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    college_id BIGINT REFERENCES public.colleges(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    year_id BIGINT REFERENCES public.cutoff_years(id) ON DELETE CASCADE,
    round TEXT NOT NULL, -- e.g., 'CAP1', 'CAP2'
    admission_type TEXT NOT NULL CHECK (admission_type IN ('CET', 'DSE', 'FIRST_YEAR_ENGINEERING', 'DIRECT_SECOND_YEAR_ENGINEERING')),
    category TEXT NOT NULL, -- e.g., 'OPEN', 'OBC', 'SC', 'ST'
    gender TEXT DEFAULT 'Co-Ed',
    cutoff_percentile NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (college_id, branch_id, year_id, round, category, gender)
);

-- ==========================================
-- 6. TABLE: predictions
-- ==========================================
CREATE TABLE public.predictions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    admission_type TEXT NOT NULL,
    entered_percentile NUMERIC NOT NULL,
    category TEXT NOT NULL,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    prediction_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 7. TABLE: prediction_results
-- ==========================================
CREATE TABLE public.prediction_results (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prediction_id BIGINT REFERENCES public.predictions(id) ON DELETE CASCADE,
    college_id BIGINT REFERENCES public.colleges(id) ON DELETE CASCADE,
    predicted_chance TEXT NOT NULL CHECK (predicted_chance IN ('Safe', 'Moderate', 'Dream')),
    probability_percentage NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 8. TABLE: saved_colleges
-- ==========================================
CREATE TABLE public.saved_colleges (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    college_id BIGINT REFERENCES public.colleges(id) ON DELETE CASCADE,
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (user_id, college_id)
);

-- ==========================================
-- 9. TABLE: college_reviews
-- ==========================================
CREATE TABLE public.college_reviews (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    college_id BIGINT REFERENCES public.colleges(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 10. TABLE: admin_uploads
-- ==========================================
CREATE TABLE public.admin_uploads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uploaded_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    file_name TEXT NOT NULL,
    year INTEGER NOT NULL,
    upload_status TEXT NOT NULL CHECK (upload_status IN ('Success', 'Pending', 'Failed')),
    imported_records INTEGER,
    failed_records INTEGER,
    duration NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- RECOMMENDED INDEXES FOR ADMISSIONS SEARCH
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_colleges_name ON public.colleges(college_name);
CREATE INDEX IF NOT EXISTS idx_colleges_city ON public.colleges(city);
CREATE INDEX IF NOT EXISTS idx_branches_name ON public.branches(branch_name);
CREATE INDEX IF NOT EXISTS idx_cutoffs_percentile ON public.cutoffs(cutoff_percentile);
CREATE INDEX IF NOT EXISTS idx_cutoffs_category ON public.cutoffs(category);
CREATE INDEX IF NOT EXISTS idx_cutoffs_gender ON public.cutoffs(gender);
CREATE INDEX IF NOT EXISTS idx_cutoffs_round ON public.cutoffs(round);
CREATE INDEX IF NOT EXISTS idx_cutoffs_college_id ON public.cutoffs(college_id);
CREATE INDEX IF NOT EXISTS idx_cutoffs_branch_id ON public.cutoffs(branch_id);
CREATE INDEX IF NOT EXISTS idx_cutoffs_year_id ON public.cutoffs(year_id);
CREATE INDEX IF NOT EXISTS idx_cutoffs_admission_type ON public.cutoffs(admission_type);

-- ==========================================
-- SUPABASE STORAGE BUCKETS CONFIGURATION
-- ==========================================
INSERT INTO storage.buckets (id, name, public) 
VALUES 
  ('college-logos', 'college-logos', true),
  ('cutoff-pdfs', 'cutoff-pdfs', true),
  ('college-images', 'college-images', true),
  ('student-documents', 'student-documents', false)
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- AUTO-SYNC USER PROFILE TRIGGER
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role, admission_type, category, gender, home_university, score, branch_preference)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
    NEW.email,
    'student',
    'CET',
    'OPEN',
    'Male',
    'SPPU (Pune)',
    0,
    'Computer Engineering'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.colleges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cutoff_years DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cutoffs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prediction_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_colleges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.college_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_uploads DISABLE ROW LEVEL SECURITY;

-- 1. Profiles Policies
CREATE POLICY "Profiles viewable by owner and admin" ON public.profiles
    FOR SELECT USING (auth.uid() = id OR role = 'admin');
CREATE POLICY "Profiles editable by owner" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- 2. Colleges Policies
CREATE POLICY "Colleges readable by everyone" ON public.colleges FOR SELECT USING (true);
CREATE POLICY "Colleges editable by admin only" ON public.colleges 
    FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- 3. Branches Policies
CREATE POLICY "Branches readable by everyone" ON public.branches FOR SELECT USING (true);
CREATE POLICY "Branches editable by admin only" ON public.branches 
    FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- 4. Cutoff Years Policies
CREATE POLICY "Cutoff years readable by everyone" ON public.cutoff_years FOR SELECT USING (true);
CREATE POLICY "Cutoff years editable by admin only" ON public.cutoff_years 
    FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- 5. Cutoffs Policies
CREATE POLICY "Cutoffs readable by everyone" ON public.cutoffs FOR SELECT USING (true);
CREATE POLICY "Cutoffs editable by admin only" ON public.cutoffs 
    FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- 6. Predictions Policies
CREATE POLICY "Predictions viewable by owner and admin" ON public.predictions
    FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Predictions insertable by owner" ON public.predictions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 7. Prediction Results Policies
CREATE POLICY "Prediction results viewable by owner and admin" ON public.prediction_results
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.predictions p 
            WHERE p.id = prediction_id AND (p.user_id = auth.uid() OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
        )
    );
CREATE POLICY "Prediction results insertable by owner" ON public.prediction_results
    FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM public.predictions p WHERE p.id = prediction_id AND p.user_id = auth.uid())
    );

-- 8. Saved Colleges Policies
CREATE POLICY "Saved colleges viewable by owner and admin" ON public.saved_colleges
    FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Saved colleges manageable by owner" ON public.saved_colleges
    FOR ALL USING (auth.uid() = user_id);

-- 9. College Reviews Policies
CREATE POLICY "Reviews viewable by everyone" ON public.college_reviews FOR SELECT USING (true);
CREATE POLICY "Reviews manageable by owner" ON public.college_reviews
    FOR ALL USING (auth.uid() = user_id);

-- 10. Admin Uploads Policies
CREATE POLICY "Admin uploads viewable by admins only" ON public.admin_uploads
    FOR SELECT USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admin uploads manageable by admins only" ON public.admin_uploads
    FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==========================================
-- 11. TABLE: admin_users
-- ==========================================
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Allow public read access to admin_users
CREATE POLICY "Allow public read access to admin_users" ON public.admin_users FOR SELECT USING (true);

-- Seed primary admin user: deveshsonawane023@gmail.com / saiyug123
INSERT INTO public.admin_users (email, password_hash, full_name, role)
VALUES ('deveshsonawane023@gmail.com', 'saiyug123', 'Devesh Sonawane', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Seed default admin user: admin@collegemate.com / admin123
INSERT INTO public.admin_users (email, password_hash, full_name, role)
VALUES ('admin@collegemate.com', '240a8e3ee40b5275e7a00f074d284a141b4a622a578cc9d2d098e914041d1df3', 'Admin User', 'admin')
ON CONFLICT (email) DO NOTHING;

